In [1]:
  import numpy as np

In [ ]:
np.__version__
np.show_config()

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
n = np.zeros(100)
print("%d bytes" % (n.size * n.itemsize))

800 bytes


In [ ]:
np.info?




In [ ]:
a = np.zeros(10)
a[4] = 1
a


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
a = np.array([[1,2,3],[3,2,1]])
a[::-1]

array([[3, 2, 1],
       [1, 2, 3]])

In [ ]:
a = np.arange(9).reshape((3,3))
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [ ]:
a = np.eye(3,3,)

In [ ]:
np.random.random([3,3,3])

array([[[0.55291973, 0.21752199, 0.02128233],
        [0.18186851, 0.220245  , 0.40703824],
        [0.20086793, 0.96469874, 0.41968882]],

       [[0.87001569, 0.81375102, 0.12385308],
        [0.22696657, 0.99162781, 0.62582667],
        [0.43407112, 0.05179168, 0.29794175]],

       [[0.11917229, 0.16352241, 0.15784029],
        [0.45850041, 0.38615126, 0.92879662],
        [0.88382294, 0.39246069, 0.36030768]]])

In [ ]:
a = np.random.random([10,10])
##a.min(),a.max()
a

array([[0.31742792, 0.29809131, 0.53125544, 0.38114553, 0.10084861,
        0.25662013, 0.83636591, 0.454962  , 0.58064655, 0.52637445],
       [0.03186912, 0.78423657, 0.04375469, 0.96655897, 0.92819146,
        0.17244085, 0.79603761, 0.89656305, 0.60578725, 0.77630093],
       [0.59656419, 0.11729666, 0.10407973, 0.73700563, 0.93723462,
        0.37078939, 0.96773436, 0.61570304, 0.12945572, 0.36786101],
       [0.12410954, 0.20030617, 0.58972253, 0.76446874, 0.33944475,
        0.3846449 , 0.66755169, 0.25775351, 0.70641254, 0.95660039],
       [0.45813726, 0.03607526, 0.17952139, 0.14903468, 0.91681105,
        0.56095337, 0.1302947 , 0.54354156, 0.9525703 , 0.34787568],
       [0.54045302, 0.91137762, 0.7255164 , 0.50206999, 0.50133345,
        0.87012113, 0.81254114, 0.9540765 , 0.5174034 , 0.51581229],
       [0.59243072, 0.68046067, 0.20900644, 0.20551724, 0.42551538,
        0.72580247, 0.5725738 , 0.21457485, 0.46241887, 0.15996244],
       [0.36759742, 0.7180391 , 0.1489248

In [ ]:
a = np.random.random(30)
a.mean()


0.48862496110634196

In [ ]:
arr = np.ones([8,8])
arr.ndim
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:

a = [[1,2],[3,4]]
np.pad(a, 5, 'constant', constant_values=0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
0 * np.nan


nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 * 0.1

False

In [ ]:
a = np.zeros((5, 5), int)
np.fill_diagonal(a, [1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
a = np.zeros((8,8))
a[::2,::2] = 1
a[1::2,1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [2]:
  a = np.unravel_index([99], (6,7,8))
  a
  

(array([1]), array([5]), array([3]))

In [3]:
iii = np.array([1,2,3,4])
iii = np.tile(iii,9).reshape(4,9)
iii

array([[1, 2, 3, 4, 1, 2, 3, 4, 1],
       [2, 3, 4, 1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4, 1, 2, 3],
       [4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [ ]:
# x =np.random.random([5,5])
# (x(random_matrix)-mean(random_matrix))/std(random_matrix))


In [ ]:
x1 = data.exel
v

![image.png](62 000 US$
64 000 US$
49 000 US$
324 000 US$
1 264 000 US$
54 330 US$
64 000 US$
51 000 US$
55 000 US$
48 000 US$
53 000 US$)

In [ ]:
x = '''62 000 US$
64 000 US$
49 000 US$
324 000 US$
1 264 000 US$
54 330 US$
64 000 US$
51 000 US$
55 000 US$
48 000 US$
53 000 US$'''

In [ ]:
x.split('\n')[1].replace('\xa', '')

SyntaxError: ignored

In [ ]:
x.split('\n')[1].replace(r'\xa', '')

'62\xa0000\xa0US$'

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_excel('/content/10_1_2_10_Standard_deviation_and_coefficient_of_variation_exercise (1).xlsx')
data

Unnamed: 0  Standard deviation and coefficient of variation  \
0          NaN  Average income in the United States and Denmark   
1          NaN                                              NaN   
2          NaN                                       Background   
3          NaN                                           Task 1   
4          NaN                                           Task 2   
5          NaN                                              NaN   
6          NaN                                           Task 3   
7          NaN                                           Task 4   
8          NaN                                              NaN   
9          NaN                                              NaN   
10         NaN                                              NaN   
11         NaN                                Annual income USA   
12         NaN                                            62000   
13         NaN                                            64000   
14         NaN                                            49000   
15         NaN                                           324000   
16         NaN                                          1264000   
17         NaN                                            54330   
18         NaN                                            64000   
19         NaN                                            51000   
20         NaN                                            55000   
21         NaN                                            48000   
22         NaN                                            53000   

                                           Unnamed: 2  \
0                                                 NaN   
1                                                 NaN   
2   You have the annual personal income of 11 peop...   
3   Decide whether you have to use sample or popul...   
4   Calculate the standard deviation of income in ...   
5                                                 NaN   
6   Calculate the coefficient of variation of inco...   
7                Try to interpret the numbers you got   
8                                                 NaN   
9                                                 NaN   
10                                                NaN   
11                                                NaN   
12                                                NaN   
13                                                NaN   
14                                                NaN   
15                                                NaN   
16                                                NaN   
17                                                NaN   
18                                                NaN   
19                                                NaN   
20                                                NaN   
21                                                NaN   
22                                                NaN   

                                           Unnamed: 3             Unnamed: 4  \
0                                                 NaN                    NaN   
1                                                 NaN                    NaN   
2                                                 NaN                    NaN   
3                                                 NaN                    NaN   
4                                                 NaN                    NaN   
5   Hint: You may start by calculating the mean an...                    NaN   
6                                                 NaN                    NaN   
7                                                 NaN                    NaN   
8                                                 NaN                    NaN   
9                                                 NaN                    NaN   
10                                                NaN                    NaN   
11                                                NaN  Annual inco

In [ ]:
us_data = data.iloc[12:,1]
dm_data = data.iloc[12:,4]

In [ ]:
dm_data

12    462852.365026
13    470317.725753
14    567367.415194
15    589763.497372
16    500179.168657
17    492713.807931
18     515109.89011
19    507644.529384
20    425525.561395
21    522575.250836
22    500179.168657
Name: Unnamed: 4, dtype: object

In [ ]:

# Task 2

np.std(us_data), np.std(dm_data)

(348285.9451349026, 43678.04182150482)

In [ ]:
# Task 3

np.std(us_data)/np.mean(us_data), np.std(dm_data)/np.mean(dm_data)

(1.8345498060574374, 0.0865031876865811)